[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "impkmeans"
version = "1.0.2"
authors = [
  { name="Ali Şenol", email="alisenol@tarsus.edu.tr" }
]
description = "ImpKMeans: Improved K-Means initialization using KDE + KD-Tree"
readme = "README.md"
requires-python = ">=3.8"
keywords = ["clustering", "kmeans", "k-means", "kde", "density", "kd-tree", "machine-learning"]
license = { file = "LICENSE" }

dependencies = [
    "numpy",
    "scikit-learn",
]

[project.urls]
"Homepage" = "https://github.com/senolali/ImpKMeans"
"Repository" = "https://github.com/senolali/ImpKMeans"
"Paper" = "https://doi.org/10.12700/aph.21.2.2024.2.6"   
